Update ManiphestExcelDefaultIncludeCustomFieldsFormat.php
neandrake/phab-utils pull request #5
Opened 2017-03-14 10:56 UTC by stevexyz

Added points + custom fields of type date formatted as date

2017-03-14 21:24 UTC, neandrake requested changes
Thank you for the submission, I think this is a good change! In general I prefer the formatting I have currently as the new lines help me visually to logically separate "actions" happening. Would you be willing to reduce the change to just the addition of the extra column and date handling?

2017-03-14 21:24 UTC, neandrake commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +      if (count($columns) > 0) {
What reason to change this? I usually prefer to break/return early and save indentation. From what I can tell nothing here changed functionally.

2017-03-14 21:24 UTC, neandrake commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +    return pht('Default with Custom Fields - extended');
If I merge this in I don't think there's any reason to have a different name

2017-03-14 21:24 UTC, neandrake commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +        'title' => pht('URI'),
I would prefer to keep ID as the first column

2017-03-14 21:24 UTC, neandrake commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +        $cellType = null;
Is there a a `PHPExcel_Cell_DataType::TYPE_DATE`?

2017-03-15 12:45 UTC, stevexyz commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +    return pht('Default with Custom Fields - extended');
Sure! In reality in my installation I kept the original and added this as new file (and for this reason I changed name)

2017-03-15 12:48 UTC, stevexyz commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +      if (count($columns) > 0) {
The break instruction (that I deleted) exits from loops, but there was no loop to exit from, and infact before removal I got a case with error that showed me that I have to correct
(PS: here in the descriptions I see red lines I didn't delete, do not know why, maybe just visualization problems)

2017-03-15 12:51 UTC, stevexyz commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +        'title' => pht('URI'),
I put first and later even made column thinner (almost disappearing). Personally I would remove (Txxx is enough as reference if needed). Depends on you needs and taste ! :)

2017-03-15 12:53 UTC, stevexyz commented on extensions/ManiphestExcelDefaultIncludeCustomFieldsFormat.php
> +        $cellType = null;
Seems not. Anyway I did coherently as in the other date fields present before!

2017-03-15 12:55 UTC, stevexyz commented
You can cherry pick the changes. Spacing removals might depend on the copy/paste I did on web i/f, I also prefer spaced! :)

2017-03-15 12:55 UTC, closed without merging